@startuml
'https://plantuml.com/class-diagram

User <|-- Post


enum Role {
Author
Reader
}

enum Status {
NEW
PROCESS
DONE
}

class User {
String login
String password
Role role
size()
}

class Post {
Date date
User user
Status status
size()
}

@enduml